set(_CATKIN_CURRENT_PACKAGE "qr")
set(qr_VERSION "0.0.0")
set(qr_MAINTAINER "psi <psi@todo.todo>")
set(qr_PACKAGE_FORMAT "2")
set(qr_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(qr_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(qr_BUILDTOOL_DEPENDS "catkin")
set(qr_BUILDTOOL_EXPORT_DEPENDS )
set(qr_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(qr_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(qr_TEST_DEPENDS )
set(qr_DOC_DEPENDS )
set(qr_URL_WEBSITE "")
set(qr_URL_BUGTRACKER "")
set(qr_URL_REPOSITORY "")
set(qr_DEPRECATED "")